---
title: "cetaceans_raster_map"
author: "Carmen Galaz-García"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(here)
library(sf)
library(fasterize)

library(rnaturalearth)
library(sp)
```


```{r}
# ----- READ IN RASTER FILES -----
raster_files <-list.files(path = here('ca_cetaceans'), full.names = TRUE)

all_whales <- raster::stack(raster_files)

```


```{r}
# ----- CALCULATING PRESENCE -------
presence <- function(x, thresh = 0.8) {
  return(ifelse(x >= thresh, 1, NA))
}

presence_layers <- calc(all_whales, fun=presence)
#plot(presence_layers)

#----- CALCULATING DIVERSITY --------
diversity <- calc(presence_layers, fun=sum, na.rm=TRUE)
#plot(diversity)

# ---- PLOTING DIVERSITY RASTER ----

#convert to data frame
diversity_df <- raster::rasterToPoints(diversity) %>%
  as.data.frame()

# make raster map
ggplot() +
  geom_raster(data = diversity_df, aes(x = x, y = y, fill = layer)) +
  scale_fill_gradient(low = 'white', high = 'blue4')+
  coord_sf(expand = 0)
  
```

```{r}
# ---- RASTER + SHAPEFILE MAP ATTEMPT 1 ----

# ca_counties <- read_sf(here("ca_counties","CA_Counties_TIGER2016.shp"))
ca_boundary <- read_sf(here("ca_state_boundary","CA_State_TIGER2016.shp"))
ggplot()+
  geom_sf(data=ca_boundary)

xlim <- c(-125,-114)
ylim <- c(32,43) 

ggplot()+
  geom_sf(data=ca_boundary)+
  geom_raster(data = diversity_df, aes(x = x, y = y, fill = layer))+
  coord_sf(xlim=xlim, ylim=ylim)


```


```{r}
# ---- RASTER + SHAPEFILE MAP ATTEMPT 2 ----
coastline110 <- ne_download(scale = 110, 
                            type = 'coastline', 
                            category = 'physical', 
                            returnclass = "sf")

plot(coastline110)

sp::plot(ne_coastline())+
  coord_sf(xlim=xlim, ylim=ylim)

  scale_fill_gradient(low = 'white', high = 'blue4')+


ggplot()+
  geom_raster(data = diversity_df, aes(x = x, y = y, fill = layer))+  
  geom_sf(data=ne_coastline(returnclass = 'sf'))+
  coord_sf(xlim=xlim, ylim=ylim)
```


